language: c

before_install:
#  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - curl -OL http://raw.github.com/lcolladotor/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
 
install:
  - ./travis-tool.sh install_bioc S4Vectors
  - ./travis-tool.sh install_bioc IRanges
  - ./travis-tool.sh install_r Matrix
  - ./travis-tool.sh install_r knitr
  - ./travis-tool.sh install_r rmarkdown
  - ./travis-tool.sh install_r knitcitations
  - ./travis-tool.sh install_r knitrBootstrap
  - ./travis-tool.sh install_github lcolladotor/derfinderHelper
  - ./travis-tool.sh install_bioc GenomeInfoDb
  - ./travis-tool.sh install_bioc AnnotationDbi
  - ./travis-tool.sh install_bioc BiocParallel
  - ./travis-tool.sh install_bioc GenomicRanges
  - ./travis-tool.sh install_bioc bumphunter
  - ./travis-tool.sh install_bioc Rsamtools
  - ./travis-tool.sh install_bioc GenomicAlignments
  - ./travis-tool.sh install_bioc rtracklayer
  - ./travis-tool.sh install_bioc GenomicFeatures
  - ./travis-tool.sh install_bioc GenomicFiles
  - ./travis-tool.sh install_r Hmisc
  - ./travis-tool.sh install_bioc qvalue
  - ./travis-tool.sh install_bioc biovizBase
  - ./travis-tool.sh install_r ggplot2
  - ./travis-tool.sh install_r testthat
  - ./travis-tool.sh install_bioc TxDb.Hsapiens.UCSC.hg19.knownGene
  - ./travis-tool.sh install_github lcolladotor/derfinder@master
  - ./travis-tool.sh install_r scales
  - ./travis-tool.sh install_r RColorBrewer
  - ./travis-tool.sh install_r reshape2
  - ./travis-tool.sh install_r plyr
  - ./travis-tool.sh install_bioc ggbio
  - ./travis-tool.sh install_github lcolladotor/derfinderPlot
  - ./travis-tool.sh install_bioc_deps

script: ./travis-tool.sh run_tests

on_failure:
  - ./travis-tool.sh dump_logs

after_script:
  - ./travis-tool.sh dump_logs_by_extension "timings"
  - ./travis-tool.sh dump_sysinfo

notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    secure: XHhGVMEFs4bAz0/ShswkQv5rXffZhLwHbPDlMA8h6pF1VOOSSz0zZblrqhyCZbF5OpsYotQZpLlGsxsVbVqTVQsuK3IVf5HWIK9HuloP091eHNVkQ46+lH6q8gT6tuWMZMrGoalrTVtlUKfAk11E2k6cYLiSdCH/22OBv58TG1w=

env:
  global:
    - R_BUILD_ARGS="--no-build-vignettes --no-manual --no-resave-data"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --timings"
    - R_CHECK_TIME="TRUE"
    - R_CHECK_TESTS="TRUE"
    - _R_CHECK_TIMINGS_="0"

